### ISSUE TITLE
ytdlBinary is not defined

### ISSUE THREAD

**Issue by evory** [przemyslawpluta/node-youtube-dl#238]
Hello, I have that error when I start my server. Don't Understand ? Any ideas ?

```
ReferenceError: ytdlBinary is not defined
    at ytdlBinary (/usr/src/app/node_modules/youtube-dl/lib/youtube-dl.js:26:22)
    at Object.<anonymous> (/usr/src/app/node_modules/youtube-dl/lib/youtube-dl.js:30:3)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/src/app/routes/rest/assets.js:4:19)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at global.app_require (/usr/src/app/index.js:3:32)
    at Object.<anonymous> (/usr/src/app/routes/rest/index.js:10:23)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at global.app_require (/usr/src/app/index.js:3:32)
    at Object.<anonymous> (/usr/src/app/routes/index.js:15:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! api.v2@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the api.v2@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I rolled back to 1.12.1 and it work fine.

**Comment by Kikobeats** [comment]
It should be fixed!

**Comment by dwasyl** [comment]
@Kikobeats Just so you know, I experienced this same problem in v2.0.0. Rolled back to 1.12.1 and everything worked fine.

**Comment by ThomasVictoria** [comment]
Appended again with the latest version, look like it is still an issue.

**Comment by Kikobeats** [comment]
- Are you using `@microlink/youtube-dl` instead of `youtube-dl`?
- What Node.js version are you using?

**Comment by dwasyl** [comment]
Node.js 8.16.0

Just `youtube-dl` as far as I can tell.

**Comment by Kikobeats** [comment]
The latest version is published at `@microlink/youtube-dl`:

```
npm install @microlink/youtube-dl
```

why? the original author doesn't give me npm permissions ¯\_(ツ)_/¯

Probably you are using a very old version. Please, see breaking changes:
https://github.com/przemyslawpluta/node-youtube-dl/releases/tag/2.0.0

After that, tell me if this is still happening!

**Comment by przemyslawpluta** [comment]
@Kikobeats you have permissions to publish for couple of months now

**Comment by arcovoltaico** [comment]
Same error both using the npm install youtube-dl or npm install @microlink/youtube-dl. 
How can I fix it? Thanks so much

**Comment by Jonybang** [comment]
there is still an error even in `@microlink/youtube-dl` package

**Comment by Jonybang** [comment]
here is my yarn.lock:
```
"@microlink/youtube-dl@^2.0.0":
  version "2.0.0"
  resolved "https://registry.yarnpkg.com/@microlink/youtube-dl/-/youtube-dl-2.0.0.tgz#0120c67949185228afe4d771cfd80719b278cd73"
  dependencies:
    hh-mm-ss "~1.2.0"
    mkdirp "~0.5.1"
    request "~2.88.0"
    streamify "~0.2.9"
```

**Comment by Jonybang** [comment]
#256 fixes issue for me

**Comment by Kikobeats** [comment]
Published at `youtube-dl@2.0.1`, can you tell me if you are still experimenting the error?
